---
- hosts: all
  tasks:
  - name: Date/time stamp for playbook start
    raw: /usr/bin/date > /home/ansible/playbook_start.log
  - name: install the apache web server
    yum:
      name: httpd
      state: latest
    notify: restart the httpd
  - name: install client software - telnet
    yum:
      name: telnet
      state: latest
  - name: log all the packages installed
    raw: yum list installed > /home/ansible/installed.log
  - name: date/time stamp or playbook end
    raw: /usr/bin/date > /home/ansible/playbook_end.log

  handlers:
  - name: restart the httpd
    service:
      name: httpd
      state: restarted
