---
- hosts: all
  vars_prompt:
  - name: package
    prompt: Enter the name of the package
  tasks:
  - name: Install "{{ package }}" server
    yum:
      name: "{{ package }}"
      state: installed
  - name: Restart "{{ package }}" service
    service:
      name: "{{ package }}"
      state: restarted
