---
- hosts: all
  gather_facts: no
  tasks:
  - name: Install Apache
    yum:
      name: httpd
      state: installed
    run_once: true
    notify: restart httpd
  handlers:
  - name: restart httpd
    service:
      name: httpd
      state: restarted
