---
- hosts: 192.168.56.101
  tasks:
  - name: Install Apache on centos
    yum:
      name: httpd
      state: latest
  - name: wait for the service to start listening on port 80
    wait_for:
      port: 80
      state: started
